sonar.projectKey=node-app

sonar.projectName=Node Application

sonar.projectVersion=1.0

sonar.sources=.

sonar.language=js

sonar.sourceEncoding=UTF-8

sonar.host.url=http://15.207.111.229:9000

sonar.login=squ_989b32cad25c126d1087148402f55d359d13c955
